### ISSUE TITLE
pleaaase ?

### ISSUE THREAD

**Issue by Kefaku** [Silabear/GoBlocks#14]
![credits](https://user-images.githubusercontent.com/114934849/202789813-0956c7c9-6492-4409-a5f8-934037ff5617.jpg)

If the MCC Discord gets its own place in the credits, why can't GitHub Contributors be there? See how this looks, like wayyyyyyyy better:

![credits2](https://user-images.githubusercontent.com/114934849/202790441-cbf11d79-fa47-4395-a640-e40c771ccae1.jpg)

Please?

**Comment by Silabear** [comment]
only joking
